
package Mill_Manager;

import static Mill_Manager.BazarUpdate.check;
import java.awt.Font;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author TAPOS DATTA
 * 
 * class MemberList show the name of member in a textarea field
 * 
 */
public class MemberList extends javax.swing.JFrame {

    /**
     * Creates new form MemberList
     */
    
    //variable declaration start
    public static MemberList memberList;
    Initialization result;
    private static int check;
    //variable declaration end
    
    /**
     * constructor of MemberList 
     * name of the fame is "LIST OF MEMBER"
     * frame Resizeable is false 
     */
    
    public MemberList() {
        super("LIST OF MEMBER");
        
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("logo.png")).getImage());
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setLocationRelativeTo(null);
        setResizable(false);
        File_Load();
       
        if(check==0){
           
            edittxtarea();
       
            write_name();
        }
    }
    
        /**
         * to check the initialization.ser file exist or not  in File_Load method
         * 
         */
    
     void File_Load(){
           
        try {
            FileInputStream fin=new FileInputStream("initialization.ser");
            ObjectInputStream out=new  ObjectInputStream(fin);
            
            try {
                 result=(Initialization) out.readObject();
                 out.close();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MillDataUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (FileNotFoundException ex) {
           
            JOptionPane.showMessageDialog(null, "Initialize data first\n Thank you");
            check=1;
            MainWindow.mainWindow.setVisible(true);
            
        } catch (IOException ex) {
            Logger.getLogger(MillDataUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     /**
      * in edittxtarea method set font of textarea 
      * editable of textarea is false;
      */
     void edittxtarea(){
          Font font=txtarea.getFont();
         float size = font.getSize() + 10.0f;
           txtarea.setFont( font.deriveFont(size) );
          
          txtarea.setEditable(false);
          
     }
    
    
     /**
      * write the member name in textarea by Write_name method 
      * 
      */
    void write_name(){
        
        txtarea.setText("");
        for(int i=0;i<result.member;i++)
        {
            String s="";
            s=(i+1)+". "+result.nameList[i];
            txtarea.append( s+ "\n");
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        updatename = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        txtarea.setBackground(new java.awt.Color(255, 153, 153));
        txtarea.setColumns(20);
        txtarea.setForeground(new java.awt.Color(0, 0, 204));
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("LIST OF MEMBER");

        updatename.setBackground(new java.awt.Color(255, 255, 51));
        updatename.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updatename.setText("EDIT NAME");
        updatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatenameActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 255, 153));
        back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(updatename, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(190, 190, 190))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * @param evt back button
     * this frame is closed and back to Main_Window frame
     */
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         MainWindow.mainWindow.setVisible(true);
            memberList.dispose();
    }//GEN-LAST:event_backActionPerformed
    
    /**
     * 
     * @param evt updatename button update the name of member 
     */
    private void updatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatenameActionPerformed
        try{
            int u= Integer.parseInt(JOptionPane.showInputDialog(null,"Enter the serial number of member"));
            if(u<1 || u>result.member) 
                throw new NullPointerException();
                
            String n=JOptionPane.showInputDialog("Update Name Of Member");
            
                if(n.isEmpty())
                throw new NullPointerException();
            
            result.nameList[u-1]=n;
            write_name();
            result.firstcolset();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please, Enter valid information");
        }
        
        file_write();
    }//GEN-LAST:event_updatenameActionPerformed
    
    /**
     * updated data is save in initialization.ser file  by file_write method  
     */
    void file_write(){
           try {
               FileOutputStream fos= new  FileOutputStream("initialization.ser");
               
               try {
                   ObjectOutputStream out=new ObjectOutputStream(fos);
                   
                   out.writeObject(result);
                   out.close();
               } catch (IOException ex) {
                   Logger.getLogger(Initial.class.getName()).log(Level.SEVERE, null, ex);
               }
           } catch (FileNotFoundException ex) {
               Logger.getLogger(Initial.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    
    /**
     * create a new JFrame in Callmemberlist method 
     */
    public static void Callmemberlist() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                memberList=new MemberList();
                if(check==0)
                    memberList.setVisible(true);
                else
                    memberList.dispose();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JButton updatename;
    // End of variables declaration//GEN-END:variables
}
